In [2]:
print("Hello Python")

Hello Python


In [4]:
# 2. 데이터 분석을 위한 파이썬 기본 문법

In [6]:
'''
리스트 = 대괄호 [] 다양한 문장, 순서를 가지고 있음 . 0123 ..
튜플 = 소괄호 () 보기만 할 수 있고 변경 추가 삭제 불가. 순서를 가지고 있음.
세트 = 중괄호 {} 순서가 없음(집합), 중복 데이터 불가능, 추가/변경/삭제 가능
딕셔너리 = 중괄호 {}, key-value 를 가진다, 순서를 가지고 있다, 변경,추가,삭제 가능
'''

'\n리스트 = 대괄호 [] 다양한 문장, 순서를 가지고 있음 . 0123 ..\n튜플 = 소괄호 () 보기만 할 수 있고 변경 추가 삭제 불가. 순서를 가지고 있음.\n세트 = 중괄호 {} 순서가 없음(집합), 중복 데이터 불가능, 추가/변경/삭제 가능\n딕셔너리 = 중괄호 {}, key-value 를 가진다, 순서를 가지고 있다, 변경,추가,삭제 가능\n'

In [7]:
# 함수
def get_char_count(lyric, char): #함수정의
    count = 0
    for i in lyric :
        if(i == char):
            count = count + 1
    return count

In [12]:
# 실행코드
lyric = """산토끼 토끼야. 어디를 가느냐. 깡총깡총 뛰면서. 어디를 가느냐.
           산 고개 고개를. 나 혼자 넘어서. 토실토실 알밤을. 주워올 테야."""

print(get_char_count(lyric,'토'))

4


In [10]:
print(get_char_count(lyric,'알'))

1


In [1]:
#연습문제 1
def americano(temp) :
    if temp >= 0 :
        print("아이스 아메리카노")
    elif temp <0 :
        print("따뜻한 아메리카노")

americano(30)


아이스 아메리카노


In [13]:
# 연습문제 1 
기온 = 0
if 기온 > 0 :
    print('아이스 아메리카노')
else :
    print('따뜻한 아메리카노')

따뜻한 아메리카노


In [16]:
# 답
def coffee(temp):
    if temp >0 :
        print("아이스 아메리카노")
    else :
        print('따뜻한 아메리카노')
        
# 함수호출
coffee(-30)

따뜻한 아메리카노


In [4]:
# 연습문제 2
def 변경성적(성적) :
    new_scores = []
    
    for s in 성적 :
        new = s + 5
        new_scores.append(new)
    return new_scores

성적 = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
new = 변경성적(성적)
print(new)

[85, 95, 75, 70, 90, 100, 95, 85, 80, 85]


In [21]:
# 답
def update_scores(scores) :
    new_scores = []
    
    for s in scores :
        new = s + 5
        new_scores.append(new)
    return new_scores

scores = [90, 80, 65, 55, 90, 95, 85]
new = update_scores(scores)
print(new)

[95, 85, 70, 60, 95, 100, 90]


In [6]:
# 연습문제 3
def change(alp) :
    uppercase = alp.upper()
    lowercase = alp.lower()
    return uppercase , lowercase

change('hungry')

('HUNGRY', 'hungry')

In [8]:
# 연습문제 4
def calculator(기호,숫자1,숫자2) :
    if 기호 == '+' :
        return 숫자1 + 숫자2
    elif 기호 == '-' :
        return 숫자1 - 숫자2
    elif 기호 == '*' :
        return 숫자1 * 숫자2
    elif 기호 == '/' :
        return 숫자1 / 숫자2
# 출력
calculator('/',2,5)

0.4

In [10]:
# 연습문제5
def plus(*숫자) :
    result = 0
    for num in 숫자 :
        result = result + num
    return result
# 출력
plus(2,4,5)

11

In [11]:
# 연습문제 6
def 권장체중(성별,키) :
    if 성별 == '여자' :
        return  (키-100)*0.9
    elif 성별 == '남자' :
        return 키 - 100
    
권장체중('여자',165)

58.5

In [14]:
# 연습문제 7
weight2 = lambda man, height : (height - 100) * 0.9 if(man) else (height - 100)

weight2(True,170) # False 인 경우 man, True 의 경우 woman

63.0

In [16]:
# 연습문제 8
d = open("abcd.txt", 'w')
d.write("A B C D E F")
d.close

<function TextIOWrapper.close()>

In [20]:
d = open("abc.txt", "r")
print(d.read())
d.close()

a,b,c,d,e


In [32]:
import numpy as np

In [33]:
list1 = [1, 2, 3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [50]:
np.zeros(2,4)

TypeError: Cannot interpret '4' as a data type

In [38]:
np.zeros(2)

array([0., 0.])

In [36]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [44]:
np.random.rand(2,3)

array([[0.48863315, 0.4792824 , 0.90902881],
       [0.53246824, 0.31026774, 0.22896751]])

In [51]:
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [55]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
arr.shape # 데이터 수를 가장 많이, 처음으로 세어보므로 중요,

(16,)

In [57]:
arr.dtype

dtype('int32')

In [58]:
arr.astype(float) # 정수 array가 실수로 바뀌는 것을 볼 수 있다.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [60]:
import numpy as np
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
# 기본 인덱스
arr[5]

5

In [62]:
arr[-1]

15

In [63]:
arr[5:8]  # 8번 바로 전까지 나온다.

array([5, 6, 7])

In [64]:
# 다차원 배열
arr2 = np.arange(16).reshape(4,4) #메서드 체인
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
arr2[1]

array([4, 5, 6, 7])

In [68]:
arr2[1][2]

6

In [67]:
arr2[0][0]

0

In [72]:
#불리언 인덱스를 사용한 선택
scores = [80, 90, 70, 65, 85, 90, 80, 75, 80, 95]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 90, 80, 75, 80, 95])

In [73]:
score_arr[score_arr >= 90]

array([90, 90, 95])

In [74]:
score_arr[score_arr >= 90] = 999

In [77]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [78]:
arr + 2

array([3, 4, 5, 6])

In [79]:
arr * 2

array([2, 4, 6, 8])

In [81]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [82]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [84]:
arr1 = np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [85]:
arr + arr1

array([ 6,  8, 10, 12])

In [87]:
list1 = [5, 6, 7, 8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [91]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [94]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [95]:
# 저장하기
np.save('array', arr)

In [96]:
load_arr = np.load('array.npy')

In [97]:
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
# 예제 3
# 함수
def change_world_case(word):
    upperCase = word.upper()
    lowerCase = word.lower()
    return upperCase, lowerCase
# 함수 호출
change_world_case("sleEPy")

('SLEEPY', 'sleepy')

In [106]:
# 예제 4 계산기 만들기
# 함수
def calculator(operator, num1, num2) :
    if(operator == '+') :
        return num1 + num2
    elif(operator == '-') :
        return num1 - num2
    elif(operator == '/') :
        return num1 / num2
    elif(operator == '*') :
        if(num2 != 0):
            return num1 * num2
    else :
        print('{} 는 연산이 불가능합니다.'.format(operator))
        
# 함수호출
calculator('*',2,6)
    

12

In [108]:
# 예제 4 입력받은 수들 모두 더하기.
def sum(*arg) : # 앞에 *을 붙여줘야 모두 더한다.
    result = 0
    for num in arg :
        result = result + num
    return result

sum(2,3,5)

10

In [111]:
# 예제 5 권장 체중 구하기
def ramda(gender, height) :
    if(gender == "남자") :
        return print(height - 100)
    elif(gender == "여자") :
        return print((height - 100) * 0.9)
    
ramda('남자',170)

70


In [110]:
# 샘플 답안
# 권장 체중을 구하는 람다식
weight2 = lambda man, height : (height - 100) * 0.9 if(man) else (height - 100)

# 람다식 실행
weight2(False, 170)

70

In [113]:
# 예제 7 쓰기모드로 열고, write() 함수를 이용해 문자를 넣기
f = open("abc.txt",'w')
f.write('a,b,c,d,e')
f.close()

In [114]:
# abc.txt 파일을 읽기모드로 열어서 읽기
f = open('abc.txt','r')
print(f.read())
f.close()

a,b,c,d,e
